/* eslint-disable react/prop-types */
import { Box, Stack, Typography } from "@mui/material";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AccessTimeRounded, CheckCircleRounded } from "@mui/icons-material";
import { EmptyReport, ReportPanel } from "./ReportPrimitives";
import { minutes, money } from "../model/statsPresentation";

const COLORS = ["#315EFB", "#FF9F1C", "#2EAD67", "#3D4650", "#8A817B", "#D8DCE1"];
export default function OperationalInsights({ operations, peakHours, ordersByStatus, summary }) {
  return <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", lg: "repeat(2,minmax(0,1fr))" }, gap: 2 }}><ReportPanel title="Velocidad operativa" subtitle="Tiempo desde que entra la orden"><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "repeat(2,minmax(0,1fr))" }, gap: 1.5 }}><Box sx={{ p: 2, bgcolor: "rgba(255,159,28,.08)", borderRadius: "10px" }}><AccessTimeRounded sx={{ color: "secondary.dark" }}/><Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1 }}>Hasta aceptar</Typography><Typography variant="h5" fontWeight={900}>{minutes(operations.averageAcceptanceMinutes)}</Typography></Box><Box sx={{ p: 2, bgcolor: "rgba(46,173,103,.08)", borderRadius: "10px" }}><CheckCircleRounded color="success"/><Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1 }}>Hasta completar</Typography><Typography variant="h5" fontWeight={900}>{minutes(operations.averageFulfillmentMinutes)}</Typography></Box></Box><Stack direction="row" justifyContent="space-between" sx={{ mt: 2 }}><Typography variant="body2" color="text.secondary">Tasa de finalización</Typography><Typography variant="body2" fontWeight={900}>{summary.completionRate}%</Typography></Stack></ReportPanel>
    <ReportPanel title="Estados de órdenes" subtitle="Distribución dentro del periodo">{ordersByStatus.length ? <Box sx={{ height: 230 }}><ResponsiveContainer><PieChart><Pie data={ordersByStatus} dataKey="value" nameKey="name" innerRadius="53%" outerRadius="78%" paddingAngle={2}>{ordersByStatus.map((item, index) => <Cell key={item.status} fill={COLORS[index % COLORS.length]}/>)}</Pie><Tooltip formatter={(value, _name, context) => [`${value} órdenes · ${context.payload.share}%`, context.payload.name]}/></PieChart></ResponsiveContainer></Box> : <EmptyReport />}</ReportPanel>
    <ReportPanel title="Horas con más movimiento" subtitle="Órdenes completadas e ingreso por hora" sx={{ gridColumn: { lg: "1 / -1" } }}>{peakHours.length ? <Box sx={{ height: { xs: 240, sm: 290 } }}><ResponsiveContainer><BarChart data={peakHours} margin={{ left: -22, right: 6 }}><CartesianGrid strokeDasharray="3 6" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip formatter={(value, name, context) => [name === "Ventas" ? money(context.payload.revenue) : value, name]}/><Bar dataKey="orders" name="Órdenes" fill="#FF9F1C" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Box> : <EmptyReport />}</ReportPanel></Box>;
}
