/* eslint-disable react/prop-types */
import { Box, LinearProgress, Paper, Stack, Typography } from "@mui/material";
import { ArrowDownwardRounded, ArrowUpwardRounded, RemoveRounded } from "@mui/icons-material";

export const ReportPanel = ({ title, subtitle, action, children, sx = {} }) => <Paper elevation={0} sx={{ p: { xs: 1.75, sm: 2.5 }, border: "1px solid", borderColor: "divider", borderRadius: 3, bgcolor: "rgba(255,255,255,.9)", ...sx }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ xs: "stretch", sm: "flex-start" }} gap={1.25} sx={{ mb: 2 }}><Box><Typography variant="subtitle1" fontWeight={850}>{title}</Typography>{subtitle && <Typography variant="caption" color="text.secondary">{subtitle}</Typography>}</Box>{action}</Stack>{children}</Paper>;

export const EmptyReport = ({ children = "Todavía no hay suficientes datos para este periodo." }) => <Box sx={{ minHeight: 190, display: "grid", placeItems: "center", textAlign: "center", px: 2 }}><Typography variant="body2" color="text.secondary">{children}</Typography></Box>;

export const KpiCard = ({ label, value, delta, helper, icon, inverse = false }) => {
  const numeric = Number(delta || 0); const favorable = inverse ? numeric <= 0 : numeric >= 0;
  return <Box sx={{ p: 2, borderRadius: 2.5, bgcolor: "rgba(255,255,255,.065)", border: "1px solid rgba(255,255,255,.11)", minWidth: 0 }}><Stack direction="row" justifyContent="space-between" gap={1}><Box minWidth={0}><Typography variant="caption" sx={{ color: "rgba(255,255,255,.62)", fontWeight: 700 }}>{label}</Typography><Typography noWrap sx={{ color: "white", fontWeight: 900, fontSize: { xs: "1.25rem", md: "1.52rem" }, letterSpacing: "-.035em", mt: .45 }}>{value}</Typography></Box><Box sx={{ color: "rgba(255,255,255,.8)", bgcolor: "rgba(255,255,255,.08)", width: 34, height: 34, display: "grid", placeItems: "center", borderRadius: 2, flexShrink: 0 }}>{icon}</Box></Stack>{delta !== undefined && <Stack direction="row" gap={.35} alignItems="center" sx={{ mt: 1.2 }}>{numeric === 0 ? <RemoveRounded sx={{ fontSize: 14 }} /> : numeric > 0 ? <ArrowUpwardRounded sx={{ fontSize: 14 }} /> : <ArrowDownwardRounded sx={{ fontSize: 14 }} />}<Typography variant="caption" sx={{ color: favorable ? "#7dda83" : "#ff8b87", fontWeight: 850 }}>{Math.abs(numeric)}%</Typography><Typography variant="caption" sx={{ color: "rgba(255,255,255,.45)" }}>vs periodo anterior</Typography></Stack>}{helper && <Typography variant="caption" sx={{ color: "rgba(255,255,255,.5)", display: "block", mt: 1.2 }}>{helper}</Typography>}</Box>;
};

export const MixRow = ({ label, value, share, helper }) => <Box><Stack direction="row" justifyContent="space-between" gap={2}><Box minWidth={0}><Typography variant="body2" fontWeight={750} noWrap>{label}</Typography>{helper && <Typography variant="caption" color="text.secondary">{helper}</Typography>}</Box><Typography variant="body2" fontWeight={850}>{value}</Typography></Stack><LinearProgress variant="determinate" value={Math.min(100, Number(share || 0))} sx={{ mt: .8, height: 6, borderRadius: 5, bgcolor: "rgba(255,159,28,.12)", "& .MuiLinearProgress-bar": { borderRadius: 5, bgcolor: "secondary.main" } }} /></Box>;
