// src/const/listas.js
const urls = [
  "https://img.freepik.com/vector-gratis/comida-bebida-logo-comida-sana-plana-dibujada-mano_23-2149632256.jpg?w=2000",
  "https://dcassetcdn.com/design_img/6165/17990/17990_139608_6165_image.jpg",
  "https://img.freepik.com/fotos-premium/diseno-grafico-ilustraciones_924318-14309.jpg?w=2000",
  "https://img.freepik.com/vector-premium/diseno-logotipo-comida-mexicana-santiago_908365-131.jpg?w=1060",
];

export const datacards = [
  {
    id: 1,
    urlImage: urls[2],
    title: "Tacos el pariente",
    emails: ["bryantsamuel.jaramillo@bbva.com", "bryantjz95@gmail.com"],
    phones: ["7223983673"],
    social: {
      facebook: "https://facebook.com/tacospariente",
      instagram: "https://instagram.com/tacospariente",
      whats: "https://api.whatsapp.com/send?phone=5217223983673&text=Hola%2C%20tienen%20servicio.%3F%20",
    },
    tags: [
      { label: "A 500m", color: "info" },
      { label: "Comida Italiana", color: "warning" },
      { label: "$70.00 - $500.00", color: "secondary" },
    ],
    isOpen: true,
    hasDelivery: true,
    likes: 42,
    schedule: {
      Lunes: { open: "09:00", close: "22:00", isOpen: true },
      Martes: { open: "09:00", close: "22:00", isOpen: true },
      Miércoles: { open: "09:00", close: "22:00", isOpen: true },
      Jueves: { open: "09:00", close: "22:00", isOpen: true },
      Viernes: { open: "09:00", close: "23:00", isOpen: true },
      Sábado: { open: "10:00", close: "23:00", isOpen: true },
      Domingo: { open: "10:00", close: "21:00", isOpen: true },
    },
    menu: [
      {
        id: 1,
        name: "Torta especial",
        description: "Salchicha con jamón, queso amarillo, cottage y pepperoni",
        price: 250.0,
        image: "https://images.unsplash.com/photo-1619096252214-ef06c45683e3?w=200",
        available: true,
        category: "Tortas",
      },
      {
        id: 2,
        name: "Torta cubana",
        description: "Pierna, salchicha, jamón, queso y aguacate",
        price: 180.0,
        image: "https://images.unsplash.com/photo-1568471173238-64ed8e813074?w=200",
        available: true,
        category: "Tortas",
      },
      {
        id: 3,
        name: "Quesadilla especial",
        description: "Queso Oaxaca con champiñones y flor de calabaza",
        price: 85.0,
        image: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=200",
        available: true,
        category: "Quesadillas",
      },
      {
        id: 4,
        name: "Tacos dorados",
        description: "Pollo deshebrado con crema y queso",
        price: 120.0,
        image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=200",
        available: true,
        category: "Tacos",
      },
    ],
  },
  {
    id: 2,
    urlImage: urls[0],
    title: "Tamales Martinez",
    emails: ["tamalitos@gmail.com"],
    phones: ["7223983673"],
    social: {
      facebook: "",
      instagram: "https://instagram.com/tamalesmartinez",
      whats: "https://api.whatsapp.com/send?phone=5217223983673",
    },
    tags: [
      { label: "A 200m", color: "info" },
      { label: "Comida Ambulante", color: "warning" },
      { label: "$10.00 - $50.00", color: "secondary" },
    ],
    isOpen: true,
    hasDelivery: false,
    likes: 128,
    schedule: {
      Lunes: { open: "06:00", close: "12:00", isOpen: true },
      Martes: { open: "06:00", close: "12:00", isOpen: true },
      Miércoles: { open: "06:00", close: "12:00", isOpen: true },
      Jueves: { open: "06:00", close: "12:00", isOpen: true },
      Viernes: { open: "06:00", close: "12:00", isOpen: true },
      Sábado: { open: "07:00", close: "13:00", isOpen: true },
      Domingo: { open: "07:00", close: "13:00", isOpen: true },
    },
    menu: [
      {
        id: 5,
        name: "Tamal verde",
        description: "Con pollo y salsa verde casera",
        price: 25.0,
        image: "https://images.unsplash.com/photo-1548340748-6d2b7d7da280?w=200",
        available: true,
        category: "Tamales",
      },
      {
        id: 6,
        name: "Tamal rojo",
        description: "Con cerdo y salsa roja",
        price: 25.0,
        image: "https://images.unsplash.com/photo-1626266061368-46a8f578ddd6?w=200",
        available: true,
        category: "Tamales",
      },
      {
        id: 7,
        name: "Atole de chocolate",
        description: "Caliente y espeso",
        price: 30.0,
        image: "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=200",
        available: true,
        category: "Bebidas",
      },
    ],
  },
  {
    id: 3,
    urlImage: urls[1],
    title: "Casa Brava",
    emails: ["casabrava@gmail.com"],
    phones: ["7223983673"],
    social: {
      facebook: "https://facebook.com/casabrava",
      instagram: "https://instagram.com/casabrava",
      whats: "https://api.whatsapp.com/send?phone=5217223983673&text=Hola%2C%20tienen%20servicio.%3F%20",
    },
    tags: [
      { label: "A 430m", color: "info" },
      { label: "Comida urbana", color: "warning" },
      { label: "$50.00 - $300.00", color: "secondary" },
    ],
    isOpen: false,
    hasDelivery: true,
    likes: 89,
    schedule: {
      Lunes: { open: "14:00", close: "22:00", isOpen: true },
      Martes: { open: "14:00", close: "22:00", isOpen: true },
      Miércoles: { open: "14:00", close: "22:00", isOpen: true },
      Jueves: { open: "14:00", close: "22:00", isOpen: true },
      Viernes: { open: "14:00", close: "23:30", isOpen: true },
      Sábado: { open: "13:00", close: "23:30", isOpen: true },
      Domingo: { open: "13:00", close: "21:00", isOpen: true },
    },
    menu: [
      {
        id: 8,
        name: "Hamburguesa clásica",
        description: "Carne de res, queso, lechuga y tomate",
        price: 120.0,
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200",
        available: true,
        category: "Hamburguesas",
      },
      {
        id: 9,
        name: "Alitas picantes",
        description: "12 piezas con salsa búfalo",
        price: 150.0,
        image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=200",
        available: true,
        category: "Entradas",
      },
      {
        id: 10,
        name: "Papas a la francesa",
        description: "Crujientes con sal de mar",
        price: 60.0,
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=200",
        available: true,
        category: "Guarniciones",
      },
    ],
  },
  {
    id: 4,
    urlImage: urls[3],
    title: "Casona de los abuelos",
    emails: ["casadelosabuelos@gmail.com"],
    phones: ["7223983673"],
    social: {
      facebook: "https://facebook.com/casonadeabuelos",
      instagram: "",
      whats: "https://api.whatsapp.com/send?phone=5217223983673",
    },
    tags: [
      { label: "A 100m", color: "info" },
      { label: "Comida Tradicional", color: "warning" },
      { label: "$30.00 - $300.00", color: "secondary" },
    ],
    isOpen: true,
    hasDelivery: false,
    likes: 215,
    schedule: {
      Lunes: { open: "08:00", close: "20:00", isOpen: true },
      Martes: { open: "08:00", close: "20:00", isOpen: true },
      Miércoles: { open: "08:00", close: "20:00", isOpen: true },
      Jueves: { open: "08:00", close: "20:00", isOpen: true },
      Viernes: { open: "08:00", close: "21:00", isOpen: true },
      Sábado: { open: "09:00", close: "21:00", isOpen: true },
      Domingo: { open: "09:00", close: "18:00", isOpen: true },
    },
    menu: [
      {
        id: 11,
        name: "Mole poblano",
        description: "Tradicional con arroz y tortillas",
        price: 180.0,
        image: "https://images.unsplash.com/photo-1599639957043-f3aa5c986398?w=200",
        available: true,
        category: "Platos fuertes",
      },
      {
        id: 12,
        name: "Pozole rojo",
        description: "Con tostadas y guarniciones",
        price: 120.0,
        image: "https://images.unsplash.com/photo-1627564803215-ad55bad5c5ea?w=200",
        available: true,
        category: "Sopas",
      },
      {
        id: 13,
        name: "Agua de horchata",
        description: "Natural de la casa",
        price: 35.0,
        image: "https://images.unsplash.com/photo-1587334207988-f9e2b8f5fc1a?w=200",
        available: true,
        category: "Bebidas",
      },
    ],
  },
];

export default datacards;